# Generated by Django 6.1.1 on 2026-09-07 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to='input_videos/')),
                ('output_video', models.FileField(blank=True, null=True, upload_to='output_videos/')),
                ('unique_potholes', models.IntegerField(default=0)),
                ('minor_potholes', models.IntegerField(default=0)),
                ('moderate_potholes', models.IntegerField(default=0)),
                ('severe_potholes', models.IntegerField(default=0)),
                ('psi', models.FloatField(default=0.0)),
                ('worst_segment', models.CharField(default='-', max_length=50)),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
