# Generated by Django 6.1.1 on 2026-09-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanreport',
            name='road_location',
            field=models.CharField(blank=True, default='Unspecified Location', max_length=255, null=True),
        ),
    ]
