# Generated by Django 6.1.1 on 2026-09-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector_app', '0002_scanreport_road_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanreport',
            name='dispatch_status',
            field=models.CharField(choices=[('Not Dispatched', 'Not Dispatched'), ('Pending Review', 'Pending Review'), ('Dispatched to Ward PWD', 'Dispatched to Ward PWD'), ('Under Maintenance', 'Under Maintenance'), ('Resolved', 'Resolved')], default='Not Dispatched', max_length=30),
        ),
        migrations.AddField(
            model_name='scanreport',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanreport',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
